### ISSUE TITLE
How to install? 

### ISSUE THREAD

**Issue by Schrank** [albertz/IdeaResolveSymlinks#1]
Awesome! <3 <3

But how to install? 😅 I'm expecting a jar file I can just throw in as a plugin?

**Comment by albertz** [comment]
There is a zipped JAR file in the releases: https://github.com/albertz/IdeaResolveSymlinks/releases

I will put that into the README.

Maybe I can also register it somehow in their listing so that you can directly install it, but I don't know how.

**Comment by Schrank** [comment]
Stupid me :D Thanks! If you put it in readme, I don't PR it :)

thanks again!

**Comment by albertz** [comment]
No problem. :)
